name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}   # <-- dodaj to

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key from secret (base64)
        run: |
          set -euxo pipefail
          umask 077
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: SSH smoke test (vvv)
        run: |
          ssh -vvv -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 -p "${{ secrets.SERVER_PORT }}" \
            "archetypy@${{ secrets.SERVER_HOST }}" "echo OK-from-Runner"

      - name: Copy deploy.sh and run it
        run: |
          scp -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_ed25519 -P "${{ secrets.SERVER_PORT }}" \
              ./deploy.sh "archetypy@${{ secrets.SERVER_HOST }}:/tmp/deploy.sh"
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_ed25519 -p "${{ secrets.SERVER_PORT }}" \
              "archetypy@${{ secrets.SERVER_HOST }}" "bash /tmp/deploy.sh"
