name: Deploy Hetman static
on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/deploy-hetman-static.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        working-directory: front
        run: |
          npm ci
          npm run build

      - name: Rsync to server (/srv/hetman/html)
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -az --delete
          path: front/dist/
          remote_path: /srv/hetman/html/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo nginx -t && sudo systemctl reload nginx
