name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-archetypy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Zapisujemy prywatny klucz z SECRET do pliku i ustawiamy prawa 600
      - name: Prepare SSH key
        shell: bash
        run: |
          set -eu
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # Prawdziwe wdrożenie – czyste SSH z -i (bez ssh-agent)
      - name: SSH deploy
        shell: bash
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          set -euxo pipefail
          ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" 'bash -s' <<'REMOTE'
          set -euxo pipefail
          cd /srv/archetypy-admin
          git config --global --add safe.directory /srv/archetypy-admin
          git fetch --all
          git reset --hard origin/main
          . .venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          sudo systemctl restart archetypy-admin
          systemctl --no-pager -l status archetypy-admin | sed -n "1,120p"
          REMOTE

      # Czekamy aż panel zacznie zwracać 200 (max ok. 90 s)
      - name: Healthcheck
        shell: bash
        run: |
          set -e
          for i in {1..30}; do
            code=$(curl -fsSLk -o /dev/null -w "%{http_code}" https://panel.archetypy.badania.pro/)
            echo "Probe $i -> HTTP $code"
            if [ "$code" = "200" ]; then
              echo "Site is healthy."
              exit 0
            fi
            sleep 3
          done
          echo "Healthcheck failed."
          exit 1
