name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH (deploy as user 'archetypy')
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:        ${{ secrets.SERVER_HOST }}
          port:        ${{ secrets.SERVER_PORT }}      # np. 22
          username:    ${{ secrets.SERVER_USER }}      # archetypy
          key:         ${{ secrets.SERVER_SSH_KEY }}   # PRYWATNY klucz
          # fingerprint: ${{ secrets.HOST_FINGERPRINT }} # "SHA256:..."
          script_stop: true
          timeout: 120s
          command_timeout: 5m
          script: |
            set -euxo pipefail
            cd /srv/archetypy-admin
            git config --global --add safe.directory /srv/archetypy-admin
            git fetch --all
            git reset --hard origin/main
            . .venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            sudo systemctl restart archetypy-admin
            systemctl --no-pager -l --lines=120 status archetypy-admin
