name: Deploy to VPS

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-archetypy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key (from secret)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          # zapis bez "echo" (żeby nie połamać nowy linii)
          printf '%s' "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # pokaż fingerprint PUBLICZNEGO klucza z secreta (kontrola)
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          echo "Runner PUBKEY FPR:"
          ssh-keygen -lf ~/.ssh/id_ed25519.pub

      - name: SSH deploy
        shell: bash
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          PORT: ${{ secrets.SERVER_PORT }}
        run: |
          set -euo pipefail
          ssh -i ~/.ssh/id_ed25519 \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=no \
              -p "$PORT" "$USER@$HOST" 'bash -s' <<'REMOTE'
          set -euxo pipefail
          cd /srv/archetypy-admin
          git config --global --add safe.directory /srv/archetypy-admin
          git fetch --all
          git reset --hard origin/main
          . .venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          sudo systemctl restart archetypy-admin || systemctl restart archetypy-admin
          systemctl --no-pager -l status archetypy-admin | sed -n "1,120p"
REMOTE

      - name: Healthcheck
        shell: bash
        run: |
          set -e
          for i in {1..30}; do
            code=$(curl -fsSLk -o /dev/null -w "%{http_code}" https://panel.archetypy.badania.pro/)
            echo "Probe $i -> HTTP $code"
            if [ "$code" = "200" ]; then
              echo "OK"
              exit 0
            fi
            sleep 3
          done
          echo "Healthcheck failed."
          exit 1
