name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-archetypy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: /usr/local/bin/archetypy-deploy

      - name: Healthcheck
        run: curl -fsS https://panel.archetypy.badania.pro/ -o /dev/null
