name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH (deploy as user 'archetypy')
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}           # 158.220.110.193
          port: ${{ secrets.SERVER_PORT }}           # 22
          username: ${{ secrets.SERVER_USER }}       # archetypy
          key: ${{ secrets.SERVER_SSH_KEY }}         # prywatny klucz z /home/archetypy/.ssh/gh_actions
          fingerprint: ${{ secrets.HOST_FINGERPRINT }} # SHA256:uAl63TfeWWEtvvpPvGPE4nZ6mcg2T4JE9jVFZTfikt0
          script_stop: true
          timeout: "120s"
          command_timeout: "15m"
          script: |
            set -euxo pipefail
            cd /srv/archetypy-admin
            git config --global --add safe.directory /srv/archetypy-admin
            git fetch --all
            git reset --hard origin/main
            . .venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            sudo systemctl restart archetypy-admin
            systemctl --no-pager -l status archetypy-admin | sed -n '1,120p'
