name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH (deploy as root, run app as 'archetypy')
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euo pipefail

            # 1) Wejście do katalogu aplikacji
            cd /srv/archetypy-admin

            # 2) Operacje GIT i PIP wykonujemy jako użytkownik 'archetypy'
            sudo -u archetypy -H bash -lc '
              set -euo pipefail
              git config --global --add safe.directory /srv/archetypy-admin
              git fetch --all
              git reset --hard origin/main

              # aktywacja venv i instalacja zależności
              . .venv/bin/activate
              pip install --no-cache-dir -r requirements.txt
            '

            # 3) Restart usługi (jako root)
            systemctl restart archetypy-admin
