[server]
address = "127.0.0.1"   # zamiast 0.0.0.0 – bezpieczniej za Nginxem
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 300

[browser]
gatherUsageStats = false
